"""Hand-authored fine-grained fact Q&A pairs for the Serendib dataset.

These complement the deterministic pairs ``build_dataset generate`` extracts from FAQ
sections and fact tables: each one pulls a specific fact (a number, a rule, a location)
that the section-level generators do not surface individually. Every ``evidence`` string
is a verbatim quote from the corresponding ``data/clean/<doc>.md``, so the answer can be
checked against the source at the human verification gate.

Fields per tuple: (doc_id, section, question, answer, evidence, answer_type)
answer_type in {"numeric", "factual", "procedural"}.
"""

AUTHORED = [
    # SGH-PI-001 — Document Library / General Information
    ("SGH-PI-001", "ABOUT SERENDIB GENERAL HOSPITAL",
     "How many beds does Serendib General Hospital have?",
     "It is a 420-bed hospital.",
     "Serendib General Hospital is a 420-bed multi-specialty private hospital", "numeric"),
    ("SGH-PI-001", "ABOUT SERENDIB GENERAL HOSPITAL",
     "In what year was Serendib General Hospital established?",
     "It was established in 1998.",
     "situated in Narahenpita, Colombo 05, established in 1998", "numeric"),
    ("SGH-PI-001", "ABOUT SERENDIB GENERAL HOSPITAL",
     "Across how many clinical departments does Serendib General Hospital provide care?",
     "Across 28 clinical departments.",
     "emergency care across 28 clinical departments", "numeric"),
    ("SGH-PI-001", "ABOUT SERENDIB GENERAL HOSPITAL",
     "What quality certification does Serendib General Hospital hold?",
     "ISO 9001:2015 certification, and it is registered with the Sri Lanka Medical Council.",
     "holds ISO 9001:2015 certification and is registered with the Sri Lanka Medical Council", "factual"),
    ("SGH-PI-001", "Visiting Hours",
     "What are the visiting hours for General Wards at Serendib General Hospital?",
     "10:00 am to 12:00 pm and 4:00 pm to 7:00 pm, daily.",
     "General Wards: 10:00 am to 12:00 pm and 4:00 pm to 7:00 pm, daily.", "numeric"),
    ("SGH-PI-001", "Visiting Hours",
     "What are the ICU and HDU visiting hours, and how many visitors are allowed at a time?",
     "11:00 am to 12:00 pm only, with one visitor permitted at a time.",
     "ICU and HDU: 11:00 am to 12:00 pm only, with one visitor permitted at a time.", "numeric"),
    ("SGH-PI-001", "Visiting Hours",
     "Can a parent stay overnight with a child in the Paediatric Ward at Serendib?",
     "Yes. One parent may remain overnight, and additional visitors are received between 3:00 pm and 6:00 pm.",
     "Paediatric Ward: One parent may remain overnight. Additional visitors are received between 3:00 pm and 6:00 pm.", "factual"),
    ("SGH-PI-001", "Visiting Hours",
     "Are children under 12 allowed to visit the ICU at Serendib General Hospital?",
     "No. Visitors below the age of 12 are not permitted in the ICU or any high-dependency unit.",
     "Visitors below the age of 12 are not permitted in the ICU or any high-dependency unit.", "factual"),
    ("SGH-PI-001", "Parking",
     "How many parking spaces are in the basement car park at Serendib General Hospital?",
     "120 spaces.",
     "Free parking is provided in the basement car park (120 spaces)", "numeric"),
    ("SGH-PI-001", "Parking",
     "How many spaces does the open-air lot on Kirula Lane have?",
     "80 spaces.",
     "the open-air lot on Kirula Lane (80 spaces)", "numeric"),
    ("SGH-PI-001", "Parking",
     "How much does the paid multi-storey parking facility cost at Serendib?",
     "LKR 50 per hour.",
     "A paid multi-storey facility is located directly opposite the main entrance, charged at LKR 50 per hour.", "numeric"),
    ("SGH-PI-001", "Parking",
     "What is the valet parking charge at Serendib General Hospital?",
     "A flat rate of LKR 200.",
     "Valet parking is available at the main entrance at a flat rate of LKR 200.", "numeric"),
    ("SGH-PI-001", "Languages",
     "Which languages are available across all clinical departments at Serendib?",
     "Sinhala, Tamil, and English.",
     "Sinhala, Tamil, and English are available across all clinical departments.", "factual"),
    ("SGH-PI-001", "Languages",
     "Can Arabic or Mandarin translation be arranged at Serendib General Hospital?",
     "Yes, with 24 hours' notice, primarily for international patients.",
     "Translation support for Arabic and Mandarin may be arranged with 24 hours' notice", "factual"),
    ("SGH-PI-001", "Medical Records",
     "How quickly can I get medical records from the last five years at Serendib?",
     "Within two working days.",
     "Records from the preceding five years are available within two working days.", "numeric"),
    ("SGH-PI-001", "Medical Records",
     "How long do older medical records take to retrieve at Serendib General Hospital?",
     "Up to five working days.",
     "Older records require up to five working days.", "numeric"),
    ("SGH-PI-001", "Medical Records",
     "What is the fee for a certified copy of medical records at Serendib?",
     "LKR 500 per request.",
     "A certified copy is issued at a fee of LKR 500 per request.", "numeric"),
    ("SGH-PI-001", "Medical Records",
     "What must I present to request my medical records at Serendib General Hospital?",
     "A valid National Identity Card or passport, at the Medical Records Office, Block A, Ground Floor.",
     "Medical Records Office, Block A, Ground Floor, upon presentation of a valid National Identity Card or passport", "procedural"),
    ("SGH-PI-001", "Second Opinions",
     "Which desk handles second-opinion requests at Serendib, and is there a fee?",
     "The Patient Services Desk at extension 1100; internal second opinions are facilitated at no additional consultation fee.",
     "contact the Patient Services Desk at extension 1100. Internal second opinions are facilitated at no additional consultation fee.", "factual"),
    ("SGH-PI-001", "Facilities for Patients with Disabilities",
     "In which consultation rooms are hearing loop systems installed at Serendib?",
     "In consultation rooms 12, 14, and 16.",
     "Hearing loop systems are installed in consultation rooms 12, 14, and 16.", "numeric"),
    ("SGH-PI-001", "Facilities for Patients with Disabilities",
     "Are guide dogs allowed at Serendib General Hospital?",
     "Yes, guide dogs are permitted on hospital premises.",
     "Guide dogs are permitted on hospital premises.", "factual"),
    ("SGH-PI-001", "Facilities for Patients with Disabilities",
     "How much notice is needed for sign language interpretation at Serendib?",
     "At least 24 hours in advance, by notifying Patient Services.",
     "Patients requiring sign language interpretation are requested to notify Patient Services at least 24 hours in advance.", "numeric"),
    ("SGH-PI-001", "Feedback and Complaints",
     "How can I submit written feedback to Serendib General Hospital by email?",
     "Written submissions are accepted at feedback@serendibhospital.lk.",
     "Written submissions are accepted at feedback@serendibhospital.lk.", "factual"),
    ("SGH-PI-001", "Feedback and Complaints",
     "Within what timeframes are complaints acknowledged and resolved at Serendib?",
     "Complaints are acknowledged within 24 hours and formally resolved within five working days.",
     "All complaints are acknowledged within 24 hours and formally resolved within five working days.", "numeric"),
    ("SGH-PI-001", "Feedback and Complaints",
     "Is a Duty Manager available at Serendib General Hospital, and when?",
     "Yes, the Duty Manager is accessible 24 hours at the main information desk.",
     "The Duty Manager is accessible 24 hours at the main information desk.", "factual"),
    ("SGH-PI-001", "24-Hour Pharmacy",
     "Where is the main 24-hour pharmacy located at Serendib General Hospital?",
     "On the Ground Floor of Block B; it operates 24 hours on all days.",
     "The main pharmacy, situated on the Ground Floor of Block B, operates 24 hours on all days.", "factual"),

    # SGH-IP-001 — Inpatient Admission Handbook
    ("SGH-IP-001", "ADMISSION PROCESS",
     "Where are planned inpatient admissions arranged at Serendib General Hospital?",
     "Through the treating consultant's office or the Surgical Admissions Desk on Level 6, Block C.",
     "Planned admissions are arranged through the treating consultant's office or the Surgical Admissions Desk on Level 6, Block C.", "factual"),
    ("SGH-IP-001", "ADMISSION PROCESS",
     "What does the admissions officer collect before a patient is taken to the ward?",
     "The admission deposit, after completing documentation and verifying insurance where applicable.",
     "verify insurance where applicable, and collect the admission deposit before the patient is escorted to the assigned ward", "procedural"),
    ("SGH-IP-001", "ADMISSION DEPOSITS",
     "Can the admission deposit be reduced or waived at Serendib General Hospital?",
     "Yes. Patients holding confirmed insurance pre-authorisation may qualify for a reduced deposit or waiver; confirmation is available from the Insurance Desk at Ext. 1200.",
     "Patients holding confirmed insurance pre-authorisation may qualify for a reduced deposit or waiver. Confirmation is available from the Insurance Desk at Ext. 1200.", "factual"),
    ("SGH-IP-001", "ITEMS TO BRING FOR ADMISSION",
     "Does Serendib General Hospital provide toiletries to inpatients?",
     "Not in General or Semi-Private Wards — patients should bring their own personal toiletries.",
     "Personal toiletries (not provided in General or Semi-Private Wards)", "factual"),
    ("SGH-IP-001", "ITEMS TO BRING FOR ADMISSION",
     "Is there a safe for valuables in the wards at Serendib General Hospital?",
     "A bedside safe is available in Private Rooms and Premium Suites only; patients are advised to leave valuables at home as the hospital accepts no liability for loss.",
     "The hospital does not accept liability for loss of personal property. A bedside safe is available in Private Rooms and Premium Suites only.", "factual"),
    ("SGH-IP-001", "DURING YOUR STAY",
     "When does the primary consultant do ward rounds at Serendib General Hospital?",
     "Once or twice daily, ordinarily between 7:00 am and 9:00 am and again between 5:00 pm and 7:00 pm.",
     "The primary consultant visits once or twice daily, ordinarily between 7:00 am and 9:00 am and again between 5:00 pm and 7:00 pm.", "numeric"),
    ("SGH-IP-001", "DURING YOUR STAY",
     "At what times are meals served to inpatients at Serendib General Hospital?",
     "At 7:30 am, 12:30 pm, and 6:30 pm.",
     "Standard meals are served at 7:30 am, 12:30 pm, and 6:30 pm.", "numeric"),
    ("SGH-IP-001", "DURING YOUR STAY",
     "Which special diets can inpatients request at Serendib General Hospital?",
     "Diabetic, low-sodium, vegetarian, halal, and soft diets, communicated to the ward nurse at admission.",
     "Dietary requirements including diabetic, low- sodium, vegetarian, halal, and soft diets are to be communicated to the ward nurse at the time of admission.", "factual"),
    ("SGH-IP-001", "DURING YOUR STAY",
     "Is Wi-Fi free for inpatients at Serendib General Hospital?",
     "Complimentary in Private Rooms and Premium Suites; in General and Semi-Private Wards, paid vouchers are LKR 200 per 24-hour period.",
     "Complimentary Wi-Fi is provided in Private Rooms and Premium Suites. Paid vouchers at LKR 200 per 24-hour period are available", "numeric"),
    ("SGH-IP-001", "DISCHARGE",
     "How long does the discharge process take at Serendib General Hospital?",
     "Typically two to four hours from the time the discharge order is signed.",
     "The discharge process typically requires two to four hours from the time the discharge order is signed.", "numeric"),
    ("SGH-IP-001", "DISCHARGE",
     "Is the outstanding balance required before discharge at Serendib General Hospital?",
     "Yes. Settlement of any outstanding balance is required before the discharge letter is released.",
     "Settlement of any outstanding balance is required before the discharge letter is released.", "procedural"),
    ("SGH-IP-001", "VISITOR POLICY",
     "How many visitors are allowed at once in a General Ward at Serendib General Hospital?",
     "A maximum of two visitors at any one time.",
     "A maximum of two visitors at any one time is permitted in General Wards.", "numeric"),
    ("SGH-IP-001", "VISITOR POLICY",
     "How many visitors are allowed in Private Rooms and Premium Suites at Serendib?",
     "Up to three visitors.",
     "Up to three visitors are permitted in Private Rooms and Premium Suites.", "numeric"),
    ("SGH-IP-001", "VISITOR POLICY",
     "Can children under 12 visit inpatients at Serendib General Hospital?",
     "Only in Private Rooms and Suites, and they must remain under direct parental supervision at all times.",
     "Children below the age of 12 may visit only in Private Rooms and Suites and must remain under direct parental supervision at all times.", "factual"),

    # SGH-PH-001 — Pharmacy Services
    ("SGH-PH-001", "PRESCRIPTION DISPENSING",
     "How long is a prescription valid at the Serendib pharmacy?",
     "30 days from the date of issue, unless otherwise indicated by the prescribing practitioner.",
     "Prescriptions are valid for 30 days from the date of issue unless otherwise indicated by the prescribing practitioner.", "numeric"),
    ("SGH-PH-001", "PRESCRIPTION DISPENSING",
     "Do I need a paper prescription for orders from Serendib consultants?",
     "No. Prescriptions issued by Serendib consultants are transmitted through the electronic prescribing system, so no paper prescription is required for internally generated orders.",
     "Patients are not required to present a paper prescription for internally generated orders.", "factual"),
    ("SGH-PH-001", "MEDICATION AVAILABILITY",
     "How many medication lines does the Serendib pharmacy formulary hold?",
     "Over 4,000 medication lines.",
     "The pharmacy maintains a formulary of over 4,000 medication lines", "numeric"),
    ("SGH-PH-001", "GENERIC SUBSTITUTION POLICY",
     "Will the Serendib pharmacy substitute a generic without asking me?",
     "No. The pharmacist proceeds with a generic substitution only with the patient's explicit consent, and patients may retain the originally prescribed brand.",
     "the dispensing pharmacist will advise the patient and proceed only with explicit consent. Patients who wish to retain the originally prescribed brand are entitled to do so.", "factual"),
    ("SGH-PH-001", "CONTROLLED SUBSTANCES",
     "What is the maximum supply of controlled medication dispensed per transaction at Serendib?",
     "A maximum of a seven-day supply, unless the prescription carries co-signature from the relevant department head.",
     "A maximum of a seven-day supply is dispensed per transaction unless the prescription carries co-signature from the relevant department head.", "numeric"),
    ("SGH-PH-001", "CONTROLLED SUBSTANCES",
     "What kinds of medications are treated as Schedule I controlled substances at Serendib?",
     "Opioid analgesics and benzodiazepines, dispensed only against an original consultant's prescription that is retained by the pharmacy.",
     "Schedule I medications, including opioid analgesics and benzodiazepines, are dispensed solely against an original consultant's prescription", "factual"),
    ("SGH-PH-001", "HOME DELIVERY SERVICE",
     "What is the minimum order value for pharmacy home delivery at Serendib?",
     "LKR 5,000.",
     "A minimum order value of LKR 5,000 applies.", "numeric"),
    ("SGH-PH-001", "HOME DELIVERY SERVICE",
     "Where and on which days does Serendib offer prescription home delivery?",
     "Within the Colombo District, Monday to Friday.",
     "Prescription delivery is available within the Colombo District on Monday to Friday.", "factual"),
    ("SGH-PH-001", "HOME DELIVERY SERVICE",
     "By what time must I order to get same-day pharmacy delivery from Serendib?",
     "Before 1:00 pm; orders received later are delivered the next working day.",
     "Same-day delivery is available for orders received before 1:00 pm; next working day for orders received thereafter.", "numeric"),
    ("SGH-PH-001", "HOME DELIVERY SERVICE",
     "Which items are not eligible for Serendib's pharmacy delivery service?",
     "Controlled medications and items requiring cold-chain storage.",
     "Controlled medications and items requiring cold-chain storage are not eligible for the delivery service.", "factual"),
    ("SGH-PH-001", "DRUG INFORMATION HELPLINE",
     "How can I reach a pharmacist for medication advice at Serendib General Hospital?",
     "A licensed pharmacist is available at Ext. 3100 during pharmacy operating hours, at no charge.",
     "medication counselling and drug interaction queries at Ext. 3100 during pharmacy operating hours", "factual"),

    # SGH-ER-001 — Emergency / Casualty (safety-critical)
    ("SGH-ER-001", "IN THE EVENT OF A MEDICAL EMERGENCY",
     "What number should I call in a medical emergency at Serendib General Hospital?",
     "Call +94 11 2 456 911 (SGH Emergency) or 110 (National).",
     "IN THE EVENT OF A MEDICAL EMERGENCY, CALL +94 11 2 456 911 (SGH EMERGENCY) OR 110 (NATIONAL).", "numeric"),
    ("SGH-ER-001", "IN THE EVENT OF A MEDICAL EMERGENCY",
     "Will emergency treatment be delayed for paperwork at Serendib General Hospital?",
     "No. Treatment will not be withheld pending administrative formalities.",
     "Treatment will not be withheld pending administrative formalities.", "factual"),
    ("SGH-ER-001", "EMERGENCY ENTRANCE AND ACCESS",
     "Where is the Serendib emergency (AEC) entrance located?",
     "On the Kirula Road side of the hospital, marked by green emergency signage and continuous floodlighting.",
     "The dedicated entrance is located on the Kirula Road side of the hospital, clearly identified by green emergency signage and continuous floodlighting.", "factual"),
    ("SGH-ER-001", "EMERGENCY ENTRANCE AND ACCESS",
     "Is the Serendib emergency department open around the clock?",
     "Yes. The Accident, Emergency and Casualty (AEC) department operates 24 hours.",
     "The Accident, Emergency and Casualty (AEC) department operates 24 hours.", "factual"),
    ("SGH-ER-001", "CONDITIONS REQUIRING IMMEDIATE AEC ATTENDANCE",
     "What are the warning signs of a suspected stroke listed by Serendib General Hospital?",
     "Sudden facial drooping, unilateral arm weakness, slurred speech, or abrupt vision loss.",
     "Suspected stroke: sudden facial drooping, unilateral arm weakness, slurred speech, or abrupt vision loss", "factual"),
    ("SGH-ER-001", "CONDITIONS REQUIRING IMMEDIATE AEC ATTENDANCE",
     "At what fever does Serendib advise immediate emergency attendance?",
     "Fever above 39°C with altered mental state or a stiff neck.",
     "Fever above 39°C with altered mental state or stiff neck", "numeric"),
    ("SGH-ER-001", "CONDITIONS REQUIRING IMMEDIATE AEC ATTENDANCE",
     "Where should I go for non-urgent concerns instead of the Serendib emergency department?",
     "Attend OPD or contact the Nurse Advice Line at Ext. 1199.",
     "patients are advised to attend OPD or contact the Nurse Advice Line at Ext. 1199", "procedural"),
    ("SGH-ER-001", "PAEDIATRIC EMERGENCY",
     "Is there a dedicated paediatric emergency area at Serendib General Hospital?",
     "Yes. A dedicated paediatric bay operates within AEC at all hours, staffed by a paediatric registrar around the clock.",
     "A dedicated paediatric bay operates within AEC at all hours, staffed by a paediatric registrar around the clock.", "factual"),
    ("SGH-ER-001", "PAEDIATRIC EMERGENCY",
     "How is the paediatric bay marked in the Serendib emergency department?",
     "Its entrance is marked with a blue floor line inside the AEC department.",
     "The paediatric bay entrance is marked with a blue floor line inside the AEC department.", "factual"),
    ("SGH-ER-001", "TRIAGE CLASSIFICATION",
     "How soon is every patient triaged on arrival at the Serendib emergency department?",
     "Within five minutes, by a triage nurse.",
     "every patient is assessed by a triage nurse within five minutes", "numeric"),
    ("SGH-ER-001", "TRIAGE CLASSIFICATION",
     "Is emergency treatment order based on arrival time at Serendib General Hospital?",
     "No. Priority of treatment is determined by clinical severity and is not based on order of arrival.",
     "Priority of treatment is determined by clinical severity and is not based on order of arrival.", "factual"),
    ("SGH-ER-001", "AEC CHARGES",
     "How is insurance handled for emergency admissions at Serendib General Hospital?",
     "Pre-authorisation may be processed after stabilisation; the Insurance Desk (Ext. 1200) initiates insurer notification once documentation is provided.",
     "Insurance pre-authorisation for emergency admissions may be processed after stabilisation. The Insurance Desk (Ext. 1200) will initiate insurer notification", "procedural"),

    # SGH-SU-001 — Surgical Procedures & Pre-Operative Care
    ("SGH-SU-001", "ESTIMATED PROCEDURE COSTS",
     "What do the surgical cost estimates at Serendib include?",
     "The surgeon's fee, anaesthetist's fee, theatre charges, and standard consumables.",
     "Costs encompass the surgeon's fee, anaesthetist's fee, theatre charges, and standard consumables.", "factual"),
    ("SGH-SU-001", "ESTIMATED PROCEDURE COSTS",
     "Which surgical costs are billed separately from the estimate at Serendib?",
     "Ward accommodation, pre-operative investigations, post-operative medication, and physiotherapy are invoiced separately.",
     "Ward accommodation, pre-operative investigations, post-operative medication, and physiotherapy are invoiced separately.", "factual"),
    ("SGH-SU-001", "PRE-OPERATIVE REQUIREMENTS",
     "When must pre-operative investigations be completed before surgery at Serendib?",
     "At least seven days before surgery; results must be reviewed and cleared before a theatre slot is confirmed.",
     "At least seven days before surgery: All pre-operative investigations ordered by the treating surgeon must be completed.", "numeric"),
    ("SGH-SU-001", "PRE-OPERATIVE REQUIREMENTS",
     "When is the pre-anaesthesia assessment required before surgery at Serendib?",
     "At least two days before surgery, with the Anaesthesiology team (Ext. 2210).",
     "At least two days before surgery: A pre-anaesthesia assessment is required with the Anaesthesiology team (Ext. 2210).", "numeric"),
    ("SGH-SU-001", "PRE-OPERATIVE REQUIREMENTS",
     "What are the fasting instructions the evening before surgery at Serendib for general anaesthesia?",
     "Patients scheduled for general anaesthesia must remain nil by mouth from midnight.",
     "The evening before surgery: Patients scheduled for general anaesthesia are to remain nil by mouth from midnight.", "procedural"),
    ("SGH-SU-001", "PRE-OPERATIVE REQUIREMENTS",
     "Where and how should a patient report on the day of surgery at Serendib?",
     "To the Surgical Admissions Desk, Level 6, Block C, at the time stated in the confirmation letter, accompanied by a responsible adult.",
     "On the day of surgery: Patients are to report to the Surgical Admissions Desk, Level 6, Block C, at the time stated in their confirmation letter.", "procedural"),
    ("SGH-SU-001", "PRE-OPERATIVE REQUIREMENTS",
     "Should a patient bring supplements to disclose at the Serendib pre-anaesthesia assessment?",
     "Yes. Patients should bring a complete list of current medications, including herbal preparations and dietary supplements.",
     "Patients are requested to bring a complete list of current medications, including herbal preparations and dietary supplements.", "procedural"),
    ("SGH-SU-001", "ESTIMATED PROCEDURE COSTS",
     "How can a patient get a price for a surgical procedure not listed at Serendib?",
     "By requesting a formal quotation from the Surgical Admissions Desk.",
     "Patients are advised to request a formal quotation from the Surgical Admissions Desk for procedures not listed below.", "procedural"),

    # SGH-FIN-001 — Insurance, Payments & Billing
    ("SGH-FIN-001", "PRE-AUTHORISATION",
     "How long does insurance pre-authorisation take at Serendib General Hospital?",
     "Ordinarily one to three working days.",
     "Processing ordinarily takes one to three working days.", "numeric"),
    ("SGH-FIN-001", "PRE-AUTHORISATION",
     "When must insurers be notified for emergency admissions at Serendib?",
     "Insurer notification is to be submitted within 24 to 48 hours of admission; emergency admissions are treated without delay pending pre-authorisation.",
     "Emergency admissions are treated without delay pending pre-authorisation. Insurer notification is to be submitted within 24 to 48 hours of admission.", "numeric"),
    ("SGH-FIN-001", "PRE-AUTHORISATION",
     "Which desk should I contact for insurance pre-authorisation guidance at Serendib?",
     "The Insurance Desk at Ext. 1200.",
     "Patients are encouraged to contact the Insurance Desk at Ext. 1200 for guidance.", "factual"),
    ("SGH-FIN-001", "ACCEPTED PAYMENT METHODS",
     "Are instalment plans available for card payments at Serendib General Hospital?",
     "Yes. Three-month interest-free instalment plans on credit cards are available for bills above LKR 100,000.",
     "Three-month interest-free instalment plans on credit cards for bills above LKR 100,000", "numeric"),
    ("SGH-FIN-001", "ACCEPTED PAYMENT METHODS",
     "How is foreign currency handled for payments at Serendib General Hospital?",
     "It is accepted (USD, EUR, GBP) at the International Patient Desk only, converted at the prevailing Sampath Bank buying rate on the day of transaction.",
     "Foreign currency (USD, EUR, GBP) | International Patient Desk only | Converted at the prevailing Sampath Bank buying rate on day of transaction", "factual"),
    ("SGH-FIN-001", "FINANCIAL ASSISTANCE",
     "What financial hardship fund does Serendib General Hospital offer?",
     "The Serendib Compassionate Care Fund, which provides partial subsidies on inpatient bills for qualifying individuals.",
     "apply to the Serendib Compassionate Care Fund, which provides partial subsidies on inpatient bills for qualifying individuals", "factual"),
    ("SGH-FIN-001", "FINANCIAL ASSISTANCE",
     "Where are Compassionate Care Fund applications received at Serendib, and how fast are they reviewed?",
     "At the Social Services Office, Block A, Ground Floor, Room 108; applications are reviewed within 48 hours.",
     "Applications are received at the Social Services Office, Block A, Ground Floor, Room 108. ... Applications are reviewed within 48 hours.", "factual"),
    ("SGH-FIN-001", "FINANCIAL ASSISTANCE",
     "What are the payment-plan terms for self-paying patients at Serendib General Hospital?",
     "For bills exceeding LKR 100,000: a minimum deposit of 50% at discharge, with the balance payable within 60 days at no interest.",
     "payment plans are also available for self-paying patients on bills exceeding LKR 100,000, with a minimum deposit of 50% at discharge and the balance payable within 60 days at no interest", "numeric"),
    ("SGH-FIN-001", "FINANCIAL ASSISTANCE",
     "What is the eligibility basis for Serendib's Compassionate Care Fund?",
     "Demonstrated financial need, Sri Lankan citizenship, and the nature of the presenting condition.",
     "Eligibility is based on demonstrated financial need, Sri Lankan citizenship, and the nature of the presenting condition.", "factual"),
    ("SGH-FIN-001", "DIRECT-BILLING INSURANCE PANELS",
     "What must a patient pay at discharge under direct billing at Serendib?",
     "Only non-covered items, co-payments, and applicable excesses.",
     "Patients are responsible only for non-covered items, co-payments, and applicable excesses at the time of discharge.", "factual"),
    ("SGH-FIN-001", "DIRECT-BILLING INSURANCE PANELS",
     "What happens if my insurer is not on Serendib's direct-billing panel?",
     "You settle the bill directly and submit a reimbursement claim to your insurer; the hospital provides the itemised bill, investigation reports, consultant letters, and discharge summary.",
     "patients are required to settle the bill directly and submit a reimbursement claim to their insurer independently", "procedural"),
    ("SGH-FIN-001", "ITEMISED BILLING",
     "Are bills itemised by default at Serendib General Hospital?",
     "Yes. All bills issued by Serendib General Hospital are itemised by default.",
     "All bills issued by Serendib General Hospital are itemised by default.", "factual"),
    ("SGH-FIN-001", "ITEMISED BILLING",
     "When must billing disputes be raised at Serendib General Hospital?",
     "At the Billing Desk before the discharge process is finalised, wherever possible.",
     "Billing disputes must be raised at the Billing Desk before the discharge process is finalised wherever possible.", "procedural"),

    # SGH-OPD-001 — Outpatient Department
    ("SGH-OPD-001", "OVERVIEW",
     "What are the Serendib OPD opening hours?",
     "Monday to Saturday from 7:30 am to 8:00 pm, and Sundays from 8:00 am to 1:00 pm.",
     "the Serendib Outpatient Department is open Monday to Saturday from 7:30 am to 8:00 pm, and on Sundays from 8:00 am to 1:00 pm", "numeric"),
    ("SGH-OPD-001", "OVERVIEW",
     "About how many outpatients does the Serendib OPD see each day?",
     "Approximately 1,200 outpatients daily, across 28 specialties.",
     "Approximately 1,200 outpatients are attended to daily across 28 specialties.", "numeric"),
    ("SGH-OPD-001", "WALK-IN PATIENTS",
     "During which peak hours can Serendib OPD walk-in waits exceed 90 minutes?",
     "10:00 am to 12:00 pm and 4:00 pm to 6:00 pm; waits may exceed 90 minutes then.",
     "During peak hours of 10:00 am to 12:00 pm and 4:00 pm to 6:00 pm, waiting times for walk-in patients may exceed 90 minutes.", "numeric"),
    ("SGH-OPD-001", "WALK-IN PATIENTS",
     "Are walk-in patients seen before or after booked patients at the Serendib OPD?",
     "After all channelled (booked) patients within each session.",
     "Walk-in patients are attended to after all channelled (booked) patients within each session.", "factual"),
    ("SGH-OPD-001", "CHANNELLING SYSTEM",
     "When does the Serendib channelling system send an SMS alert?",
     "When three patients remain ahead of the patient's slot.",
     "An automated SMS notification is sent to the patient when three patients remain ahead of their slot", "numeric"),
    ("SGH-OPD-001", "DOCUMENTS TO BRING TO OPD",
     "Which document is mandatory for registration at the Serendib OPD?",
     "A National Identity Card or Passport.",
     "National Identity Card or Passport (mandatory for registration)", "factual"),

    # SGH-LAB-001 — Laboratory & Diagnostic Services
    ("SGH-LAB-001", "COLLECTING RESULTS",
     "How soon are lab results available on the Serendib patient portal?",
     "Within one hour of verification.",
     "Results are accessible via the Serendib patient portal within one hour of verification.", "numeric"),
    ("SGH-LAB-001", "COLLECTING RESULTS",
     "How are abnormal or critical lab results communicated at Serendib General Hospital?",
     "By telephone to the referring consultant without delay.",
     "Abnormal or critical results are communicated by telephone to the referring consultant without delay.", "factual"),
    ("SGH-LAB-001", "COLLECTING RESULTS",
     "What must a patient present to collect printed lab or radiology results at Serendib?",
     "Their NIC or hospital registration card, at the laboratory or radiology desk.",
     "Patients may collect printed results from the laboratory or radiology desk upon presentation of their NIC or hospital registration card.", "procedural"),
    ("SGH-LAB-001", "LABORATORY TESTS AND TURNAROUND TIMES",
     "What is the turnaround time for a routine blood panel (FBC, ESR, CRP) at Serendib?",
     "2 to 4 hours.",
     "Routine Blood Panel | FBC, ESR, CRP | 2 to 4 hours", "numeric"),
    ("SGH-LAB-001", "IMAGING SERVICES",
     "What preparation is required before an abdominal ultrasound at Serendib?",
     "A 4-hour fast and a full bladder (for pelvic scans, a full bladder only).",
     "Ultrasound | Abdominal: 4-hour fast and full bladder; Pelvic: full bladder only", "procedural"),
    ("SGH-LAB-001", "FASTING REQUIREMENTS BY TEST",
     "How long must I fast before a lipid profile at Serendib General Hospital?",
     "10 to 12 hours; water is permitted.",
     "Lipid Profile | Yes | 10 to 12 hours; water permitted", "numeric"),

    # FAQ docs — a few distinct fine-grained numeric facts
    ("SGH-FAQ-002", "BOOKING AN APPOINTMENT",
     "What is the late-cancellation fee for an appointment at Serendib General Hospital?",
     "A LKR 500 administrative fee for cancellations within two hours of the appointment, applied to the next booking.",
     "Late cancellations within two hours attract a LKR 500 administrative fee, which is applied to the next booking.", "numeric"),
    ("SGH-FAQ-002", "BOOKING AN APPOINTMENT",
     "How early should I arrive for a booked appointment at Serendib General Hospital?",
     "At least 20 minutes before the session begins, at the OPD Registration Desk.",
     "advised to arrive at the OPD Registration Desk at least 20 minutes before their session begins", "numeric"),
    ("SGH-FAQ-002", "BOOKING AN APPOINTMENT",
     "How soon is an appointment confirmation SMS sent at Serendib General Hospital?",
     "Within 15 minutes of any online or telephone booking.",
     "A confirmation SMS is sent within 15 minutes of any online or telephone booking.", "numeric"),
    ("SGH-FAQ-002", "BOOKING AN APPOINTMENT",
     "What is the fee for a follow-up appointment at Serendib General Hospital?",
     "50% of the applicable consultation fee, for a return visit to the same consultant within 30 days for the same condition.",
     "A follow-up appointment is a return visit to the same consultant within 30 days of the original consultation for the same condition. The fee for a follow-up is 50% of the applicable consultation fee.", "numeric"),
    ("SGH-FAQ-002", "BOOKING AN APPOINTMENT",
     "What is the appointment hotline number at Serendib General Hospital and its hours?",
     "0112-456-789, available 7:00 am to 8:00 pm daily.",
     "calling the appointment hotline at 0112-456-789 (available 7:00 am to 8:00 pm daily)", "numeric"),

    # SGH-FAQ-003 — Surgery & Pre-Operative Care (fine-grained)
    ("SGH-FAQ-003", "BEFORE SURGERY",
     "What is the Surgical Helpline number at Serendib General Hospital?",
     "0112-456-800.",
     "Patients may also contact the Surgical Helpline directly at 0112-456-800.", "numeric"),
    ("SGH-FAQ-003", "BEFORE SURGERY",
     "How long before the theatre date must pre-operative results be cleared at Serendib?",
     "At least 48 hours before the scheduled theatre date, cleared by the consultant.",
     "All results must be submitted and cleared by the consultant at least 48 hours before the scheduled theatre date.", "numeric"),
    ("SGH-FAQ-003", "BEFORE SURGERY",
     "Which medications commonly need adjusting before surgery at Serendib General Hospital?",
     "Anticoagulants such as warfarin and aspirin, antidiabetic agents including insulin, and some antihypertensive drugs — none stopped without explicit instruction.",
     "These commonly include anticoagulants such as warfarin and aspirin, antidiabetic agents including insulin, and some antihypertensive drugs.", "factual"),
    ("SGH-FAQ-003", "BEFORE SURGERY",
     "Can I drink water before general anaesthesia surgery at Serendib?",
     "Patients must be nil by mouth from midnight, but clear water may be permitted up to two hours before the procedure in some cases, as confirmed by the anaesthesiology team.",
     "Clear water may be permitted up to two hours before the procedure in some cases", "numeric"),
    ("SGH-FAQ-003", "BEFORE SURGERY",
     "What items must be removed before entering the theatre at Serendib General Hospital?",
     "Dentures, hearing aids, and contact lenses must be removed; valuables, jewellery, and nail polish should be left at home.",
     "Dentures, hearing aids, and contact lenses must be removed before entering the theatre.", "procedural"),
    ("SGH-FAQ-003", "ON THE DAY AND AFTER",
     "What is day-case surgery at Serendib General Hospital?",
     "A procedure where the patient is admitted, operated on, monitored in recovery, and discharged on the same calendar day without an overnight stay.",
     "Day-case surgery refers to procedures where the patient is admitted, operated upon, monitored in the recovery room, and discharged on the same calendar day without an overnight stay.", "factual"),
    ("SGH-FAQ-003", "ON THE DAY AND AFTER",
     "Which procedures are commonly done as day cases at Serendib General Hospital?",
     "Cataract surgery, minor orthopaedic procedures, and selected laparoscopic operations.",
     "Common day-case procedures at Serendib include cataract surgery, minor orthopaedic procedures, and selected laparoscopic operations.", "factual"),
    ("SGH-FAQ-003", "ON THE DAY AND AFTER",
     "At what post-operative temperature should I contact the Serendib Surgical Helpline?",
     "A fever above 38.5°C after discharge — contact the Surgical Helpline at 0112-456-800 before presenting to Accident and Emergency.",
     "Patients experiencing post-operative fever above 38.5°C, wound discharge, unusual or worsening pain ... contact the Surgical Helpline at 0112-456-800", "numeric"),
    ("SGH-FAQ-003", "ON THE DAY AND AFTER",
     "How soon can patients return to activity after minor versus major surgery at Serendib?",
     "Minor procedures may allow light activity within one to two weeks; major joint replacements or cardiac surgery may require six to twelve weeks of graduated rehabilitation.",
     "minor procedures may allow return to light activity within one to two weeks, whereas major joint replacements or cardiac surgery may require six to twelve weeks of graduated rehabilitation", "numeric"),
    ("SGH-FAQ-003", "ON THE DAY AND AFTER",
     "Is the Serendib Surgical Helpline staffed around the clock?",
     "Yes, the helpline is staffed 24 hours and will direct the patient appropriately.",
     "The helpline is staffed 24 hours and will direct the patient appropriately.", "factual"),
    ("SGH-FAQ-003", "ON THE DAY AND AFTER",
     "Can I request a specific surgeon at Serendib General Hospital?",
     "Yes. Patients may request a specific surgeon at consultation; if unavailable, an alternative of equivalent seniority and subspecialty experience is offered.",
     "Patients are free to request a specific surgeon at the time of consultation.", "factual"),
    ("SGH-FAQ-003", "BEFORE SURGERY",
     "What pre-operative investigations are typically needed before surgery at Serendib?",
     "Typically a full blood count, blood group and crossmatch, ECG, chest X-ray, and relevant biochemistry, with the exact panel specified by the consultant.",
     "typically include a full blood count, blood group and crossmatch, ECG, chest X-ray, and relevant biochemistry", "factual"),

    # SGH-FAQ-004 — Inpatient Admission (fine-grained)
    ("SGH-FAQ-004", "WARDS AND ROOMS",
     "How many inpatient accommodation categories does Serendib General Hospital offer?",
     "Four: General Ward, Semi-Private Ward, Private Room, and Premium Suite (ICU and HDU placements are clinically determined).",
     "Serendib General Hospital offers four inpatient accommodation categories: General Ward (4-bed ...), Semi-Private Ward (2-bed ...), Private Room ..., and Premium Suite", "numeric"),
    ("SGH-FAQ-004", "WARDS AND ROOMS",
     "How do I upgrade my room after admission at Serendib General Hospital?",
     "Request it through the ward nurse or the Admissions Desk (Ext. 1050); an additional deposit is collected for the difference between ward categories.",
     "Room upgrades ... must be requested through the ward nurse or the Admissions Desk (Ext. 1050). An additional deposit is collected", "procedural"),
    ("SGH-FAQ-004", "WARDS AND ROOMS",
     "In which wards can a family member stay overnight at Serendib General Hospital?",
     "One adult companion may stay overnight in Private Rooms and Premium Suites; not in General or Semi-Private Wards, except a parent in the Paediatric Ward. ICU and HDU allow no overnight companions.",
     "One adult companion may remain overnight in Private Rooms and Premium Suites.", "factual"),
    ("SGH-FAQ-004", "DURING THE STAY",
     "How can an interpreter be arranged for an inpatient at Serendib General Hospital?",
     "Through the Patient Services Desk (Ext. 1100).",
     "the Patient Services Desk (Ext. 1100) can arrange this", "factual"),
    ("SGH-FAQ-004", "DURING THE STAY",
     "Can an inpatient take temporary leave from the ward at Serendib General Hospital?",
     "Only with approval from the treating consultant or on-call medical officer and a signed leave form; patients on IV drips, active monitoring, or post-operative observation are not eligible.",
     "This must be approved by the treating consultant or the on-call medical officer, and the patient must sign a leave form", "factual"),
    ("SGH-FAQ-004", "DISCHARGE",
     "How soon after discharge are records available on the Serendib patient portal?",
     "Within 24 hours of discharge.",
     "All records are also accessible through the patient portal within 24 hours of discharge.", "numeric"),
    ("SGH-FAQ-004", "WARDS AND ROOMS",
     "Which special diets can be requested for an inpatient at Serendib General Hospital?",
     "Diabetic, low-sodium, low-fat, vegetarian, vegan, halal, and soft or pureed diets, communicated to the ward nurse at admission.",
     "diabetic, low-sodium, low-fat, vegetarian, vegan, halal, and soft or pureed diets must be communicated to the ward nurse at admission", "factual"),
    ("SGH-FAQ-004", "DURING THE STAY",
     "Is the Serendib patient portal free to access from the wards?",
     "Yes. The internal patient portal is accessible on all wards through the Serendib Wi-Fi network at no charge.",
     "The hospital's internal patient portal is accessible on all wards through the Serendib Wi-Fi network at no charge.", "factual"),
    ("SGH-FAQ-004", "DURING THE STAY",
     "Where are mobile phones not permitted for inpatients at Serendib General Hospital?",
     "In the ICU and HDU; mobile phone use is permitted in all other wards.",
     "Mobile phone use is permitted in all wards except the ICU and HDU.", "factual"),

    # SGH-FAQ-005 — Laboratory Tests & Results (fine-grained)
    ("SGH-FAQ-005", "BOOKING AND PREPARATION",
     "Which laboratory tests can I self-refer for at Serendib General Hospital?",
     "A limited range of wellness screening tests: full blood count, fasting blood glucose, lipid profile, and basic thyroid function.",
     "Self-referral is accepted for a limited range of wellness screening tests, including full blood count, fasting blood glucose, lipid profile, and basic thyroid function.", "factual"),
    ("SGH-FAQ-005", "BOOKING AND PREPARATION",
     "Do I need a referral for a CT, MRI, or ultrasound at Serendib General Hospital?",
     "Yes. For imaging such as CT, MRI, and ultrasound, a medical referral is required in all cases.",
     "For imaging such as CT, MRI, and ultrasound, a medical referral is required in all cases.", "factual"),
    ("SGH-FAQ-005", "BOOKING AND PREPARATION",
     "What are the home sample collection hours and booking requirements at Serendib?",
     "Within the Colombo District, Monday to Saturday from 6:00 am to 10:00 am; advance booking is required by calling 0112-456-770 at least one day prior, and a home visit fee applies.",
     "Home visit sample collection is available for blood and urine tests within the Colombo District, Monday to Saturday from 6:00 am to 10:00 am. Advance booking is required by calling 0112-456-770 at least one day prior.", "numeric"),
    ("SGH-FAQ-005", "BOOKING AND PREPARATION",
     "How should I prepare for a contrast-enhanced CT scan at Serendib General Hospital?",
     "Fast for at least four hours and provide a recent creatinine result; patients on metformin follow specific discontinuation instructions from the radiology team.",
     "For contrast-enhanced CT scans, patients must fast for at least four hours before the procedure and provide a recent creatinine result", "procedural"),
    ("SGH-FAQ-005", "BOOKING AND PREPARATION",
     "What must MRI patients disclose before scanning at Serendib General Hospital?",
     "Any implanted metallic devices — including pacemakers, cochlear implants, or surgical clips — must be notified to the radiology team in advance, as certain implants may contraindicate MRI.",
     "Patients with any implanted metallic devices, including pacemakers, cochlear implants, or surgical clips, must notify the radiology team in advance.", "factual"),
    ("SGH-FAQ-005", "RESULTS AND FOLLOW-UP",
     "How long are laboratory results stored at Serendib General Hospital?",
     "For a minimum of seven years, in accordance with regulatory requirements.",
     "All investigation results are stored in the patient's hospital record for a minimum of seven years", "numeric"),
    ("SGH-FAQ-005", "RESULTS AND FOLLOW-UP",
     "How quickly are X-ray reports ready at Serendib General Hospital?",
     "Typically within two hours; MRI and CT reports within 24 hours.",
     "Radiology reports for X-rays are typically ready within two hours; MRI and CT reports within 24 hours.", "numeric"),
    ("SGH-FAQ-005", "RESULTS AND FOLLOW-UP",
     "How long do microbiology cultures take at the Serendib laboratory?",
     "24 to 72 hours, depending on the organism.",
     "Microbiology cultures require 24 to 72 hours depending on the organism.", "numeric"),
    ("SGH-FAQ-005", "RESULTS AND FOLLOW-UP",
     "Can I get a second opinion on a radiology report at Serendib General Hospital?",
     "Yes, by requesting a review by a senior or subspecialty radiologist; external second opinions are provided on a CD or via secure digital transfer on written request, and a fee may apply for external transfer.",
     "Second opinions on radiology reports may be arranged within the department by requesting a review by a senior or subspecialty radiologist.", "factual"),
    ("SGH-FAQ-005", "RESULTS AND FOLLOW-UP",
     "How are self-referred patients notified of abnormal lab results at Serendib?",
     "Self-referred patients are contacted by a clinician before results appear on the portal.",
     "Self- referred patients will be contacted by a clinician before results appear on the portal.", "factual"),
    ("SGH-FAQ-005", "BOOKING AND PREPARATION",
     "How long must I fast before a glucose tolerance test at Serendib General Hospital?",
     "An 8-hour fast before arriving; the procedure involves multiple blood draws over two hours.",
     "For a glucose tolerance test, an 8-hour fast is required before arriving; the procedure involves multiple blood draws over two hours.", "numeric"),

    # SGH-FAQ-006 — Insurance & Payments (fine-grained)
    ("SGH-FAQ-006", "INSURANCE",
     "What are the Insurance Desk hours at Serendib General Hospital?",
     "Monday to Friday, 8:00 am to 5:00 pm, at Ext. 1200.",
     "The Insurance Desk at Ext. 1200 (Monday to Friday, 8:00 am to 5:00 pm) can assist", "numeric"),
    ("SGH-FAQ-006", "INSURANCE",
     "What must I present at admission to activate direct billing at Serendib?",
     "A valid insurance card and pre-authorisation letter.",
     "Patients must present a valid insurance card and pre-authorisation letter at admission to activate direct billing.", "procedural"),
    ("SGH-FAQ-006", "INSURANCE",
     "Does basic health insurance usually cover OPD consultations at Serendib?",
     "Usually not — most basic plans in Sri Lanka cover inpatient treatment only; outpatient coverage requires an outpatient rider or comprehensive plan.",
     "Most basic health insurance plans in Sri Lanka cover inpatient treatment only.", "factual"),
    ("SGH-FAQ-006", "INSURANCE",
     "Where can I get a written cost estimate for a planned procedure at Serendib?",
     "From the Billing Desk (Ext. 1210), covering surgical fees, theatre charges, estimated ward accommodation, and investigation costs.",
     "The Billing Desk (Ext. 1210) can provide a written cost estimate for any planned procedure", "factual"),
    ("SGH-FAQ-006", "PAYMENTS AND BILLING",
     "What is the admission deposit range at Serendib General Hospital?",
     "From LKR 25,000 for a General Ward to LKR 150,000 for a Premium Suite, and LKR 100,000 for ICU or HDU.",
     "Deposits range from LKR 25,000 for a General Ward to LKR 150,000 for a Premium Suite, and LKR 100,000 for ICU or HDU.", "numeric"),
    ("SGH-FAQ-006", "PAYMENTS AND BILLING",
     "How are confirmed billing errors and overpayments handled at Serendib?",
     "If a billing error is confirmed, the correction is applied before the final invoice and any overpayment is refunded within five working days.",
     "any overpayment is refunded within five working days", "numeric"),
    ("SGH-FAQ-006", "PAYMENTS AND BILLING",
     "How quickly are billing queries resolved at Serendib General Hospital?",
     "Straightforward queries are resolved the same day; queries requiring clinical verification within 24 hours.",
     "Straightforward queries are resolved on the same day. Queries requiring clinical verification are resolved within 24 hours.", "numeric"),
    ("SGH-FAQ-006", "PAYMENTS AND BILLING",
     "What is the fee for additional documentation from the Serendib Medical Records Office?",
     "LKR 500 per document, available within five working days.",
     "requested through the Medical Records Office within five working days at a fee of LKR 500 per document", "numeric"),
    ("SGH-FAQ-006", "PAYMENTS AND BILLING",
     "Does Serendib General Hospital withhold care for an unpaid bill?",
     "No. The hospital does not withhold medical care or necessary treatment for an outstanding balance, but discharge documentation and prescriptions are released only on settlement or a formally agreed payment arrangement.",
     "The hospital does not withhold medical care or necessary treatment on the grounds of an outstanding balance.", "factual"),
    ("SGH-FAQ-006", "PAYMENTS AND BILLING",
     "After how long are unresolved outstanding balances referred to recovery at Serendib?",
     "After 60 days.",
     "Unresolved outstanding balances may be referred to the hospital's recovery process after 60 days.", "numeric"),
    ("SGH-FAQ-006", "PAYMENTS AND BILLING",
     "What documents does Serendib provide at discharge for an insurance reimbursement claim?",
     "A final itemised bill, copies of investigation reports, the signed discharge summary, pharmacy receipts, and where applicable surgeon's and anaesthetist's fee notes.",
     "the hospital provides a final itemised bill, copies of all investigation reports generated during admission, the discharge summary signed by the treating consultant, pharmacy receipts", "factual"),

    # SGH-ER-001, SGH-LAB-001, SGH-OPD-001, SGH-PI-001 — a few more facts
    ("SGH-ER-001", "CONDITIONS REQUIRING IMMEDIATE AEC ATTENDANCE",
     "What symptoms accompanying chest pain warrant immediate emergency attendance at Serendib?",
     "Chest pain or tightness, particularly when accompanied by sweating, nausea, or breathlessness.",
     "Chest pain or tightness, particularly when accompanied by sweating, nausea, or breathlessness", "factual"),
    ("SGH-ER-001", "CONDITIONS REQUIRING IMMEDIATE AEC ATTENDANCE",
     "What signs of a severe allergic reaction require emergency attendance at Serendib?",
     "Facial or throat swelling or difficulty swallowing.",
     "Severe allergic reaction, including facial or throat swelling or difficulty swallowing", "factual"),
    ("SGH-ER-001", "EMERGENCY ENTRANCE AND ACCESS",
     "Should emergency patients use the main hospital lobby at Serendib General Hospital?",
     "No. The main hospital lobby is not to be used for emergency presentations; walk-in patients use the glass doors marked “Accident and Emergency.”",
     "The main hospital lobby is not to be used for emergency presentations.", "factual"),
    ("SGH-LAB-001", "LOCATIONS AND OPERATING HOURS",
     "What are the routine sample collection hours at the Serendib laboratory?",
     "6:00 am to 8:00 pm daily.",
     "Sample collection: 6:00 am to 8:00 pm daily.", "numeric"),
    ("SGH-LAB-001", "LOCATIONS AND OPERATING HOURS",
     "Is emergency laboratory testing available around the clock at Serendib?",
     "Yes. The emergency laboratory (urgent results) operates 24 hours.",
     "Emergency laboratory (urgent results): 24 hours.", "factual"),
    ("SGH-LAB-001", "LOCATIONS AND OPERATING HOURS",
     "What are the radiology and imaging hours at Serendib General Hospital?",
     "Monday to Saturday 7:00 am to 8:00 pm and Sunday 8:00 am to 2:00 pm, with emergency imaging available 24 hours via on-call radiographer.",
     "Monday to Saturday: 7:00 am to 8:00 pm. Sunday: 8:00 am to 2:00 pm. Emergency imaging: 24 hours via on-call radiographer.", "numeric"),
    ("SGH-LAB-001", "IMAGING SERVICES",
     "What is the report turnaround for an MRI at Serendib General Hospital?",
     "24 hours; the scan itself takes 45 to 90 minutes and no ferromagnetic implants are permitted.",
     "MRI | No ferromagnetic implants permitted; procedure duration 45 to 90 minutes | 24 hours", "numeric"),
    ("SGH-OPD-001", "OVERVIEW",
     "How close are the channelling desk, laboratory, pharmacy, and cashier to the Serendib OPD exit?",
     "All are within 50 metres of the OPD exit.",
     "the channelling desk, laboratory sample collection point, pharmacy counter, and cashier are all within 50 metres of the OPD exit", "numeric"),
    ("SGH-OPD-001", "OVERVIEW",
     "Which floors of Block A does the Serendib OPD occupy?",
     "The Ground Floor and Level 1 of Block A.",
     "The OPD occupies the Ground Floor and Level 1 of Block A.", "factual"),
    ("SGH-PI-001", "Appointment Booking",
     "Where can walk-in patients register for an appointment at Serendib General Hospital?",
     "At the OPD Registration Desk, Ground Floor, Block A.",
     "Walk-in registration is available at the OPD Registration Desk, Ground Floor, Block A.", "factual"),
    ("SGH-PI-001", "24-Hour Pharmacy",
     "What are the satellite pharmacy hours at Serendib General Hospital?",
     "The satellite pharmacy on Level 4, adjacent to the Surgical Wards, operates from 6:00 am to 10:00 pm.",
     "A satellite pharmacy on Level 4, adjacent to the Surgical Wards, operates from 6:00 am to 10:00 pm.", "numeric"),
]
